 <!DOCTYPE html>
 <html lang="en">

 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Avatar</title>
 </head>

 <body>

     <?= $svg ?>

     <form action="avatar.php" method="post">
         <fieldset>
             <legend>Créez votre Avatar</legend>
             <select name="size" id="size">
                 <option value="">-- Taille --</option>
                 <option value="2">2</option>
                 <option value="3">3</option>
                 <option value="4">4</option>
                 <option value="5">5</option>
                 <option value="6">6</option>
                 <option value="7">7</option>
                 <option value="8">8</option>
                 <option value="9">9</option>
                 <option value="10">10</option>
             </select>
             <select name="color" id="color">
                 <option value="">-- Nombre de couleurs --</option>
                 <option value="2">2</option>
                 <option value="3">3</option>
                 <option value="4">4</option>
                 <option value="5">5</option>
                 <option value="6">6</option>
                 <option value="7">7</option>
                 <option value="8">8</option>
                 <option value="9">9</option>
                 <option value="10">10</option>
             </select>
             <input type="submit" value="Générer">
             <input type="submit" value="Télécharger">
         </fieldset>
     </form>

 </body>

 </html>